# Generated by Django 5.1.1 on 2024-10-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('category', models.CharField(choices=[('science: math', 'Science: Math'), ('geography', 'Geography'), ('general knowledge', 'General Knowledge')], max_length=50)),
            ],
        ),
    ]
