# Generated by Django 5.1.1 on 2024-10-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_backend', '0002_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='category',
            field=models.CharField(choices=[('science: mathematics', 'Science: Mathematics'), ('geography', 'Geography'), ('general knowledge', 'General Knowledge')], max_length=50),
        ),
    ]
